language: python
sudo: false
python:
- pypy
- 2.7
- pypy3
- 3.6
- 3.7
- 3.8
- 3.9
env:
  global:
  - PG_URL="postgresql:///enum34_test"
  - MYSQL_URL="mysql+mysqlconnector://root@localhost/enum34_test"
  - TEST_DATABASE_URLS="$PG_URL $MYSQL_URL"
  matrix:
  - SQLALCHEMY_VER=">=1.3.0,<1.4.0"
  - SQLALCHEMY_VER=">=1.4.0,<2.0.0"
services:
- postgresql
- mysql
before_install:
- export PY=`python -c 'import sys; print("pypy" if hasattr(sys,"pypy_version_info") else "%d.%d" % sys.version_info[:2])'`
- export PY_VER=`python -c 'import sys; print("%d.%d" % sys.version_info[:2])'`
- echo "PY='$PY'"
- echo "PY_VER='$PY_VER'"
install:
- pip install -U pip setuptools wheel
- pip install -U "SQLAlchemy $SQLALCHEMY_VER"
- pip install -U -e .
- pip install -U pytest flake8 pytest-cov codecov
- if [[ "$PY" = "pypy" ]]; then
    pip install psycopg2cffi;
  else
    pip install psycopg2-binary;
  fi
- if [[ "$PY" = "pypy" ]]; then
    pip install PyMySQL;
    export TEST_DATABASE_URLS="${TEST_DATABASE_URLS/mysqlconnector/pymysql}";
  else
    pip install mysql-connector-python;
  fi
before_script:
- createdb -E utf8 -T postgres enum34_test
- mysql -e 'CREATE DATABASE enum34_test;'
script:
- python -m pytest --cov sqlalchemy_enum34.py --durations=10 test.py
- flake8 .
after_success:
- codecov
